# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce506937b4f86d3c279dc17412f3aad61c22eabd59d9f12f29361c5ea3dcf969c28a3a1076c5e719cc543338c2ac911b43852b220bb0f7089bf93a60e72f8c1

test:
  secret_key_base: eb4044e8e943efb846caa1f069f29228385d7bc2c9fa684c988322d914ffca6bcf20146e2a42b2353473751dc01b6e3e813a0b6f2411237038a17be7106072a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
